services:

  Dbp\Relay\VerityBundle\Service\:
    resource: '../../Service'
    autowire: true
    autoconfigure: true

  Dbp\Relay\VerityBundle\ApiResource\:
    resource: '../../ApiResource'
    autowire: true
    autoconfigure: true

  Dbp\Relay\VerityBundle\State\:
    resource: '../../State'
    autowire: true
    autoconfigure: true

  Dbp\Relay\VerityBundle\EventSubscriber\:
    resource: '../../EventSubscriber'
    autowire: true
    autoconfigure: true
    tags: [kernel.event_listener]